#Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1604"
  config.vm.network "private_network", ip: "192.168.33.10"
  #config.vm.provider "virtualbox" do |vb|
  config.vm.provider "libvirt"  do |vb|
    vb.memory = "8056"
    vb.cpus = 4
  config.vm.provider :virtualbox do |vb|
        vb.name = "spinnaker"
  end
end
 config.vm.provision "shell", path: "install-spinnaker.sh"
end

